# Generated by Django 2.0 on 2018-05-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180530_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursement',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='matter',
            name='trust',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
