# Generated by Django 2.0 on 2018-06-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180530_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
