# Generated by Django 2.0 on 2018-06-07 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180606_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discount_choice', models.CharField(choices=[('Percentage', 'Percentage'), ('Flat', 'Flat')], max_length=20, verbose_name='Percentage of Flat?')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='disbursement',
            options={'ordering': ('date',)},
        ),
        migrations.AlterModelOptions(
            name='matter',
            options={'ordering': ('invoice_date',)},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('date',)},
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='discount',
        ),
        migrations.AddField(
            model_name='matter',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Discount'),
        ),
    ]
