# Generated by Django 2.0 on 2018-08-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20180715_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
